### PR TITLE
Exclude bots from having their commits validated

### PR DESCRIPTION
**Pull request by icatalina**
So we can use `dependabot`

@davidchin @deini @PascalZajac @lord2800

### CODE REVIEW

**Comment by icatalina** [comment]
cc: @precariouspanther

**Comment by icatalina** [comment]
Test run of that change:

```~dev/validate-commits dependabot/npm_and_yarn/tar-2.2.2
❯ git log --format=%an -10
dependabot-preview[bot]
Ignacio Catalina
Ignacio Catalina
Ignacio Catalina
David Chin
David Chin
David Chin
David Chin
David Chin
David Chin

~dev/validate-commits dependabot/npm_and_yarn/tar-2.2.2
❯ git log --format=%an -10 --author=\\[bot\\] --invert-grep
Ignacio Catalina
Ignacio Catalina
Ignacio Catalina
David Chin
David Chin
David Chin
David Chin
David Chin
David Chin
David Chin```

**Comment by precariouspanther** [comment]
Thanks for the update @icatalina but lets avoid steamrolling changes like this - you went from proposed change to merged within 30 minutes for something that wasn't a hotfix, which prevents others from being able to provide meaningful feedback.

This is a benign change so no need to revert, but please keep this in mind for future build changes. At least give it a day so other offices have the chance to add any feedback.

**Comment by PascalZajac** [comment]
It does, it's up to each team to opt-in. For me this is a pretty uncontroversial change, but one I can see people wanting to take advantage of.

**Comment by precariouspanther** [comment]
@PascalZajac definitely, and if the merge PR's are open for 24 hours (i.e into BCApp) then 👍 from me.

**Comment by icatalina** [comment]
Hi @precariouspanther! Sorry if this PR got merged too quickly to give feedback. I did rush it a bit because there are plenty of PRs all across the org with failing tests due to the lack of support from the commit-validation.

As you and @PascalZajac pointed out this is just adding the functionality to the tool, we now need to update it on the individual repos, where we can discuss the change.

**Comment by precariouspanther** [comment]
@icatalina all good, as I mentioned in my "edit" I didn't notice until after I'd submitted the feedback that this wasn't on the bigcommerce/bigcommerce repo 😃

**Pull request merged**
